# exp config
exp_name: 'asl_right_1'
seed: 0
dataset: 'shrec21'
save_folder_path: './experiments/'

# data config
data:
 data_dir: '/home/atefeh/AG-MAE/data/asl/Booth_Results/MAE_finger_tapping/all_pose'
 train_data_dir: '/home/atefeh/AG-MAE/data/asl/train'
 test_data_dir: '/home/atefeh/AG-MAE/data/asl/test/'
 step: 1
 normalize: False
 mean: [0, 0, 0]
 std: [0, 0, 0]
 n_joints: 21
 label_map: [0,1,2,3,4]            
 joints_connections: [[0, 1], [1, 2], [2, 3], [3, 4], [0, 5], [5, 6], [6, 7], [7, 8], [5, 9], [9, 10], [10, 11], [11, 12], [9, 13], [13, 14], [14, 15], [15, 16], [13, 17], [17, 18], [18, 19],[19, 20],[0,17]]

# stmae model config
stmae:
 num_joints: 21
 coords_dim: 3
 encoder_embed_dim: 256
 encoder_depth: 6
 num_heads: 8
 mlp_dim: 512
 decoder_dim: 64
 decoder_depth: 6
 window_size: 16
 masking_strategy: 'random'
 spatial_masking_ratio: 0.6
 temporal_masking_ratio: 0.6
 anatomical_loss: True
 root_index: 0
 num_epochs: 200
 lr: 1e-3
 weight_decay: 0.05
 batch_size: 128

## offline stgcn model configs
stgcn_offline:
 sequence_length: 80
 task: 'class'
 num_classes: 17
 num_epochs: 200
 lr: 1e-3
 weight_decay: 0.005
 batch_size: 8
 
## online stgcn model configs
stgcn_online:
 window_size: 16
 min_seq_length: 80
 max_seq_length: 10
 task: 'both'
 num_classes: 18
 num_epochs: 30
 lr: 1e-3
 weight_decay: 0.005
 batch_size: 128
